### ISSUE TITLE
Bug in ARC cache

### ISSUE THREAD

**Issue by ghaering** [bluele/gcache#11]
The ARC does not work if keys expire. I haven't looked into the implementation, but here's how to trigger the bug:

	cache := gcache.New(1000).ARC().Expiration(0).Build()
	cache.Set("foo", "bar")
	cache.Get("foo")
	cache.Set("foo", "bar")

I'll also file a pull request that adds this as a test.

**Comment by bluele** [comment]
@ghaering Thanks! PR https://github.com/bluele/gcache/pull/13 solves this issue.
