### ISSUE TITLE
ARC.Len() and ARC.GetAll() returns expired item/count

### ISSUE THREAD

**Issue by fogywang** [bluele/gcache#17]
First, thanks for the contributors to provide expirable cache on LRU/LFU/ARC.

Here's an issue I encounter while using ARC cache:
After items in ARC cache being all expired (confirmed that Get() cannot get any value), Len() still returns the length as if items weren't expired.
Same as GetAll(), it returns a map containing items that are supposed to be all expired.

**Comment by bluele** [comment]
Thanks. Let me check the issue.

**Comment by bluele** [comment]
This issue is fixed by #18
