### ISSUE TITLE
Panic when removing item from ARC cache

### ISSUE THREAD

**Issue by dmotylev** [bluele/gcache#26]
`2017/04/11 15:08:16 http: panic serving 127.0.0.1:59608: interface conversion: interface {} is string, not *gcache.arcItem
goroutine 130 [running]:
net/http.(*conn).serve.func1(0xc420192000)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0x183
panic(0x4909480, 0xc420162900)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2f0
github.com/redsift/flexo-botfwk/vendor/github.com/bluele/gcache.(*ARC).remove(0xc42032c210, 0x48cd620, 0xc42058ef30, 0x480a963)
	/Users/dmotylev/Workshop/go/src/github.com/redsift/flexo-botfwk/vendor/github.com/bluele/gcache/arc.go:258 +0x9f9
github.com/redsift/flexo-botfwk/vendor/github.com/bluele/gcache.(*ARC).Remove(0xc42032c210, 0x48cd620, 0xc42058ef30, 0xc42058ef00)
	/Users/dmotylev/Workshop/go/src/github.com/redsift/flexo-botfwk/vendor/github.com/bluele/gcache/arc.go:244 +0x9c`

**Comment by bluele** [comment]
Thanks for your issue.
I was able to reproduce this. This issue will be resolved by #25.
