### ISSUE TITLE
LoaderFunc define expiry?

### ISSUE THREAD

**Issue by sajal** [bluele/gcache#28]
Just discovered this library and seems useful for what I'd like to do.

I noticed in #25 , functionality was added to allow user defined expiry per item.  The `SetWithExpire` methods. Can we extend this to `LoaderFunc`?

```
type LoaderFuncWithExpire func(interface{}) (interface{}, time.Duration, error)
```

Unrelated question: If my `LoaderFunc` is very slow, and there are multiple `Get` for same key, will gcache run the `LoaderFunc` multiple times, or only once and send same output to all callers?

**Comment by bluele** [comment]
Hi, @sajal .
Thank you for your question.

> Can we extend this to LoaderFunc?

Yes, you can. Could you implement this feature? Or I will implement.

> Unrelated question: If my LoaderFunc is very slow, and there are multiple Get for same key, will gcache run the LoaderFunc multiple times, or only once and send same output to all callers?

If getting same key at the same time, LoaderFunc run only once and send same output to all callers.
Please see this link(https://github.com/bluele/gcache/blob/master/singleflight.go#L43) for more detail.

**Comment by sajal** [comment]
@bluele : Thanks for the information.

> Yes, you can. Could you implement this feature? Or I will implement.

I will look into implementing it (and getting acquainted with the codebase) once I am sure I'm gonna use this library. Just exploring for now.

**Comment by bluele** [comment]
@sajal (Thanks, @anpryl )
This feature is added at #29 .
