### ISSUE TITLE
Feature Request: Allowing for unbounded cache size

### ISSUE THREAD

**Issue by pcman312** [bluele/gcache#34]
Being forced to provide a cache size during construction of the cache doesn't work well for our particular use case. The size of our cache is bounded in other more real-world ways and we don't need to worry about the cache growing out of control. To that end, I'd like to request a new function on the cache builder to allow for no max cache size. The `New()` method could be changed such that it allows for <=0 size that is interpreted as unbounded.

**Comment by aaronwinter** [comment]
Agreed. This is something I have been wondering as well. I am not too sure what purpose `SimpleCache` serves as it is. Especially since a gorountine-safe map is coming soon (see: https://github.com/golang/go/issues/18177). 

If @bluele is ok with this, I'd like to modify `SimpleCache` to be unbounded by default.

**Comment by bluele** [comment]
It's a nice feature.
Let's add this feature to all types, not just simple cache type.

**Comment by aaronwinter** [comment]
@bluele Why though? Does it make sense to have allow an unbounded LRU/LFU/ARC cache. Eviction will just never happen. In that scenario, it is more than likely that this is an error that should be reported.

**Comment by pcman312** [comment]
I agree with @aaronwinter. If you are never evicting from the cache, the method of evicting (LRU, LFU, ARC) doesn't matter.

**Comment by bluele** [comment]
Thanks @aaronwinter and @pcman312 .
That's true. There seems to be no case to use evicting with expiration only, so it should only be implemented to Simple cache.

@aaronwinter 
If there is no other problem, could you implement this feature and its test?

**Comment by aaronwinter** [comment]
@bluele Cool, thanks for the quick reply. I will work on this (along other features on my backlog) this week-end.

**Comment by aaronwinter** [comment]
This issue can be closed. Addressed in #38
