### ISSUE TITLE
ARC cache does not work as expected (when used with expiry)

### ISSUE THREAD

**Issue by deepakprabhakara** [bluele/gcache#52]
Consider this modified test:-
```func TestARCLength(t *testing.T) {
	gc := buildLoadingARCacheWithExpiration(20, 1*time.Second)
	gc.Get("test1")
	gc.Get("test2")
	length := gc.Len()
	expectedLength := 2
	if length != expectedLength {
		t.Errorf("Expected length is %v, not %v", expectedLength, length)
	}
	time.Sleep(2 * time.Second)
	length = gc.Len()
	expectedLength = 0
	if length != expectedLength {
		t.Errorf("Expected length is %v, not %v", expectedLength, length)
	}

	gc.Get("test1")
	length = gc.Len()
	expectedLength = 1
	if length != expectedLength {
		t.Errorf("Expected length is %v, not %v", expectedLength, length)
	}
	gc.Get("test2")
	length = gc.Len()
	expectedLength = 2
	if length != expectedLength {
		t.Errorf("Expected length is %v, not %v", expectedLength, length)
	}
}
```

Adding back test1 and test2 after they have expired doesn't return a length of 2 as expected. It looks like there is an issue with adding an entry that has expired.

**Comment by aaronwinter** [comment]
Thanks for reporting this, I was able to reproduce it on my machine. I will investigate this.

**Comment by aaronwinter** [comment]
Looks like the ARC cache completely falls apart when expirable entries are enabled.

https://github.com/bluele/gcache/blob/master/arc.go#L122

```
if elt := c.b2.Lookup(key); elt != nil {
		fmt.Println("@@@@ key:", key)
		fmt.Println("@@@@@ elt:", elt)
		c.part = maxInt(0, c.part-maxInt(c.b1.Len()/c.b2.Len(), 1))
		c.replace(key)
		c.b2.Remove(key, elt)
		c.t2.PushFront(key)
		return item, nil
	}
```

Zooming on `c.replace(key)` (https://github.com/bluele/gcache/blob/master/arc.go#L40):

```
func (c *ARC) replace(key interface{}) {
	var old interface{}
	if (c.t1.Len() > 0 && c.b2.Has(key) && c.t1.Len() == c.part) || (c.t1.Len() > c.part) {
		old = c.t1.RemoveTail()
		c.b1.PushFront(old)
	} else if c.t2.l.Len() > 0 {
		old = c.t2.RemoveTail()
		c.b2.PushFront(old)
	} else {
		return
	}

        // old = "test1"
	item, ok := c.items[old]
	if ok {
		delete(c.items, old)
		if c.evictedFunc != nil {
			c.evictedFunc(item.key, item.value)
		}
	}
}
```

Zooming further down that execution path:

```
else if c.t2.l.Len() > 0 {
		old = c.t2.RemoveTail()
		c.b2.PushFront(old)
	}
```

I'm not clear on whether the `t2` sub-ARC cache should be filled up at all (before entries become eligible for eviction) in which case the logic fails in the way data is balanced/distributed among the sub-caches *or* if `(c.t1.Len() > 0 && c.b2.Has(key) && c.t1.Len() == c.part) || (c.t1.Len() > c.part)` should evaluate to true.

@bluele can you look into this or give me a high-level overview of the right behavior for ARC internals?

**Comment by deepakprabhakara** [comment]
Thanks @aaronwinter @bluele for looking into this.

**Comment by aaronwinter** [comment]
I think @bluele must be very busy at the moment. I'm not clear on whether he plans to keep maintaining this project going further.

@skurfuerst I will fix that this week. I need some time to draft a correct implementation and then implement the expirable entries features, write more extensive tests etc.

**Comment by bluele** [comment]
Sorry for very late response.
This issue is solved by https://github.com/bluele/gcache/pull/58.
