### ISSUE TITLE
increment method in lfu.go cause memory leak

### ISSUE THREAD

**Issue by Neoysx** [bluele/gcache#64]
After init a lfu cache, i set some values in it. Then i get them frequently(like 400000 times), the memory grows very fast.
![image](https://user-images.githubusercontent.com/23695839/70959718-eb7a8280-20b7-11ea-9e5b-9d4a184311d6.png)
![image](https://user-images.githubusercontent.com/23695839/70959864-4b712900-20b8-11ea-8ec9-b3d3508e4b16.png)

**Comment by bluele** [comment]
Probably duplicates this issue: https://github.com/bluele/gcache/issues/71#issuecomment-778717715
