### ISSUE TITLE
how to share between multiple processes?

### ISSUE THREAD

**Issue by juneng603** [bluele/gcache#68]
Hi, gcache developers!!

I hope to use a gcache in multiprocesses. 
By the way, I'm thinking about how I can share a cache store in every process (there is a single parent process and multiple child processes).

When I wrote C++ before, I used shared memory to share it between processes, and I'm working on a project to move to Golang, and I'm thinking about a good way. 

I'm thinking about gcache, is there an appropriate way?

**Comment by leezhu** [comment]
I think you can realize it use goroutine other than mutiprocess. Or Redis /memcache fit you

hope to help you

**Comment by bluele** [comment]
Currently, gcache only supports multiple goroutine in a single process.
