### ISSUE TITLE
问下啊，初始化的size参数单位是缓存个数还是容量啊

### ISSUE THREAD

**Issue by ayamzh** [bluele/gcache#76]
问下啊，初始化的size参数单位是缓存个数还是容量啊

**Comment by TracyBin** [comment]
Although we are both Chinese, we can hardly get answers to questions in Chinese

**Comment by susnow** [comment]
i have the same problem, what's means of the size when call gcache.New() func
file capacities or cache count? 
if file capacities, which kind unit of it? b or kb or the others?

**Comment by TracyBin** [comment]
I recently read the source code. There is a linked list inside. This size represents the size of the linked list, which is the size of the key  that can be cached.When the number of cached keys is greater than size, the eviction strategy is triggered

**Comment by pakano** [comment]
缓存个数！
![图片](https://user-images.githubusercontent.com/52499820/199203518-c78fbfdd-e169-48d3-9b70-6da4c6a5f431.png)
